test: Add policy tests to provider and core
cloudquery/.github pull request #64
Opened 2022-05-06 16:43 UTC by shimonp21

2022-05-06 17:27 UTC, shimonp21 commented
please dont review yet

2022-05-09 12:04 UTC, erezrokah requested changes
Thanks @shimonp21, great to have theses tests 🧪 

Left some comments. Please let me know what you think (some might be relevant to other files in this repo too, so I'll look into that).

2022-05-09 12:04 UTC, erezrokah commented on workflows/repo-specific/cloudquery/policy_test.yml
> +          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
```suggestion
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
```

(or we should update the matrix)

2022-05-09 12:04 UTC, erezrokah commented on workflows/repo-specific/cloudquery/policy_test.yml
> +        platform: [ ubuntu-latest]
What do you think about using a matrix to run this in parallel?

```suggestion
        dbversion: ['postgres:latest']
        go: ['1.17']
        platform: [ ubuntu-latest]
        provider: ['aws', 'gcp', 'azure', 'k8s']
```

Then `go run ./main.go provider build-schema ${{ matrix.provider }}` etc.

This works since the provider name matches the policy name, but we can also use a tuple ([provider, policy]) in the future if needed

2022-05-09 12:04 UTC, erezrokah commented on workflows/repo-specific/cloudquery/policy_test.yml
> +  unitests:
```suggestion
  policy-tests:
```

2022-05-10 06:21 UTC, erezrokah approved these changes

2022-05-10 06:25 UTC, merged